include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true