name: restaurant_reservation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  flutter_svg: ^2.0.1
  geolocator: ^13.0.2
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0+3

  # Icons
  iconsax_plus: ^1.0.0

  # State Management Bloc
  bloc: ^9.0.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #---------- LOCAL ASSETS ----------#

  assets:
    - assets/logos/
    - assets/fonts/
    - assets/images/
    - assets/images/onboarding/
  
#---------- LOCAL FONTS ----------#
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700