name: restaurant_reservation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  flutter_svg: ^2.0.1
  cached_network_image: ^3.4.1

  # Icons
  iconsax_plus: ^1.0.0

  # State Management Bloc
  bloc: ^9.0.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
